package unet.simulacion.encelado.vista;

import java.awt.Color;
import java.awt.event.ActionListener;
import java.awt.event.KeyListener;
import java.text.DecimalFormat;
import javax.swing.*;
import javax.swing.event.ChangeListener;
import unet.simulacion.encelado.modelo.Chorro;
import unet.simulacion.encelado.modelo.Simulacion;

/**
 *
 * @author Personal
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    private Simulacion simulacion;
    private DecimalFormat format;

    /**
     * Creates new form NewJFrame
     */
    public VentanaPrincipal(KeyListener keyListener,
            ActionListener actionListener,
            ChangeListener changeListener,
            Simulacion simulacion) {
        initComponents();
        format = new DecimalFormat("#,##0.00");
        addKeyListener(keyListener);
        jPanel1.addKeyListener(keyListener);
        pausaItem.addActionListener(actionListener);
        empujeXNeg.addChangeListener(changeListener);
        empujeXPos.addChangeListener(changeListener);
        empujeYPos.addChangeListener(changeListener);
        empujeYNeg.addChangeListener(changeListener);
        relacionTiempo.addChangeListener(changeListener);

        this.simulacion = simulacion;
        alturaY.setEditable(false);
        posicionX.setEditable(false);
        velocidadX.setEditable(false);
        velocidadY.setEditable(false);
        tiempo.setMaximum(simulacion.tiempoTotal);
        combustible.setMaximum(simulacion.getNave().pesoCombustibleInicial);
        combustible.setValue(simulacion.getNave().pesoCombustibleInicial);
        empujeYPos.setValue(simulacion.getNave().getEmpujeYPositivo());
        empujeYNeg.setValue(simulacion.getNave().getEmpujeYNegativo());
        empujeXPos.setValue(simulacion.getNave().getEmpujePositivo());
        empujeXNeg.setValue(simulacion.getNave().getEmpujeNegativo());
        relacionTiempo.setValue(simulacion.getRelacionMiliSeg());
        //relacionTiempo.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        alturaY = new javax.swing.JTextField();
        empujeYPos = new javax.swing.JSpinner();
        velocidadY = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        empujeYNeg = new javax.swing.JSpinner();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        posicionX = new javax.swing.JTextField();
        empujeXPos = new javax.swing.JSpinner();
        velocidadX = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        empujeXNeg = new javax.swing.JSpinner();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        combustible = new javax.swing.JProgressBar();
        tiempo = new javax.swing.JProgressBar();
        estatus = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        relacionTiempo = new javax.swing.JSlider();
        jLabel5 = new javax.swing.JLabel();
        tiempoProximoChorro = new javax.swing.JProgressBar();
        exito = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        pausaItem = new javax.swing.JCheckBoxMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        salirItem = new javax.swing.JMenuItem();
        ayudaMenu = new javax.swing.JMenu();
        ayudaItem = new javax.swing.JMenuItem();
        acercaDeItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Y"));

        jLabel6.setText("Velocidad (m/s)");

        jLabel7.setText("Empuje Pos (Kg.m/s)");

        jLabel8.setText("Altura (Km)");

        alturaY.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        empujeYPos.setModel(new javax.swing.SpinnerNumberModel(0, 0, 1000000, 100));

        velocidadY.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel13.setText("Empuje Neg (Kg.m/s)");

        empujeYNeg.setModel(new javax.swing.SpinnerNumberModel(0, 0, 1000000, 100));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(velocidadY)
                    .addComponent(alturaY)
                    .addComponent(empujeYPos, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(empujeYNeg))
                .addContainerGap())
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel13, jLabel6, jLabel7, jLabel8});

        jPanel3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {alturaY, empujeYNeg, empujeYPos, velocidadY});

        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(velocidadY, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(alturaY, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(empujeYPos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(empujeYNeg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {alturaY, empujeYNeg, empujeYPos, jLabel13, jLabel6, jLabel7, jLabel8, velocidadY});

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("X"));

        jLabel9.setText("Velocidad (m/s)");

        jLabel10.setText("Empuje Pos (Kg.m/s)");

        jLabel11.setText("Posicion (Km)");
        jLabel11.setToolTipText("");

        posicionX.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        empujeXPos.setModel(new javax.swing.SpinnerNumberModel(0, 0, 1000000, 1));

        velocidadX.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel12.setText("Empuje Neg (Kg.m/s)");

        empujeXNeg.setModel(new javax.swing.SpinnerNumberModel(0, 0, 1000000, 1));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(empujeXNeg, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(velocidadX, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(empujeXPos, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(posicionX, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel4Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel10, jLabel11, jLabel9});

        jPanel4Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {empujeXNeg, empujeXPos, posicionX, velocidadX});

        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(velocidadX, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(posicionX, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(empujeXPos, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(empujeXNeg, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {empujeXPos, jLabel10, jLabel11, jLabel9, posicionX, velocidadX});

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Progreso"));

        jLabel3.setText("Tiempo (seg)");

        jLabel4.setText("Combustible (Kg)");

        combustible.setString("0");
        combustible.setStringPainted(true);

        tiempo.setString("0");
        tiempo.setStringPainted(true);

        estatus.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "En Ejecución", "Pausado", "Fin de Simulacion" }));
        estatus.setEnabled(false);

        jLabel1.setText("Tiempo Proximo Chorro");

        jLabel2.setText("Estado");

        relacionTiempo.setMaximum(1000);
        relacionTiempo.setMinimum(1);
        relacionTiempo.setMinorTickSpacing(1);
        relacionTiempo.setToolTipText("El valor sera la cantidad de milisegundos para un segundo normal");
        relacionTiempo.setValue(1000);

        jLabel5.setText("Relacion Tiempo (1 s ES 1 ms)");
        jLabel5.setToolTipText("");

        tiempoProximoChorro.setString("0");
        tiempoProximoChorro.setStringPainted(true);

        exito.setBackground(new java.awt.Color(255, 51, 51));
        exito.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exito.setText("Mision sin exito");
        exito.setOpaque(true);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(relacionTiempo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(estatus, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(combustible, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tiempo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tiempoProximoChorro, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(exito, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel5Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel1, jLabel2, jLabel3, jLabel4, jLabel5});

        jPanel5Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {combustible, estatus, relacionTiempo, tiempo, tiempoProximoChorro});

        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tiempo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combustible, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(tiempoProximoChorro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(estatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(relacionTiempo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(exito)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel5Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {combustible, estatus, exito, jLabel1, jLabel2, jLabel3, jLabel4, jLabel5, relacionTiempo, tiempo, tiempoProximoChorro});

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenu1.setText("Archivo");

        pausaItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, 0));
        pausaItem.setText("Pausa");
        jMenu1.add(pausaItem);
        jMenu1.add(jSeparator1);

        salirItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0));
        salirItem.setText("Salir");
        salirItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirItemActionPerformed(evt);
            }
        });
        jMenu1.add(salirItem);

        jMenuBar1.add(jMenu1);

        ayudaMenu.setText("Ayuda");

        ayudaItem.setText("Ayuda");
        ayudaItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ayudaItemActionPerformed(evt);
            }
        });
        ayudaMenu.add(ayudaItem);

        acercaDeItem.setText("Acerca de...");
        acercaDeItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acercaDeItemActionPerformed(evt);
            }
        });
        ayudaMenu.add(acercaDeItem);

        jMenuBar1.add(ayudaMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ayudaItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ayudaItemActionPerformed
        JOptionPane.showMessageDialog(this,
                "La simulación consta de un cohete situado en la atmósfera de la de la Luna Enceládo de Saturno que "
                + "busca recolectar partículas que salen de los chorros de vapor de la superficie"
                + "de la luna. El cohete cuenta con controles para aumentar o disminuir el empuje"
                + "con el cual se desplaza la nave. A su vez permite la visualización de "
                + "los parámetros básicos como velocidad, tiempo, cantidad de combustible entre otros.",
                "Ayuda", JOptionPane.QUESTION_MESSAGE);
    }//GEN-LAST:event_ayudaItemActionPerformed

    private void acercaDeItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acercaDeItemActionPerformed
        JOptionPane.showMessageDialog(this,
                "Simulación de cohete situado en la atmósfera de la Luna Enceládo de Saturno. \n\n"
                + "Orlando Becerra\n"
                + "Colomba Wolleter\n"
                + "Prof: Feijo Colomine",
                "Acerca de...", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_acercaDeItemActionPerformed

    private void salirItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_salirItemActionPerformed

    public JCheckBoxMenuItem getPausa() {
        return pausaItem;
    }

    public JSpinner getEmpujeYPos() {
        return empujeYPos;
    }

    public JSpinner getEmpujeYNeg() {
        return empujeYNeg;
    }

    public JSpinner getEmpujeXPos() {
        return empujeXPos;
    }

    public JSpinner getEmpujeXNeg() {
        return empujeXNeg;
    }

    public JSlider getTiempoRelacion() {
        return relacionTiempo;
    }

    public JPanel getDibujo() {
        return jPanel1;
    }

    public void update() {

        tiempo.setString(simulacion.getTiempoActual1() + " / " + simulacion.tiempoTotal);
        tiempo.setValue(simulacion.getTiempoActual1());

        jLabel5.setText("Relacion Tiempo (1 seg ES A " + simulacion.getRelacionMiliSeg() + " ms)");

        combustible.setString("" + simulacion.getNave().getPesoConbustible());
        combustible.setValue(simulacion.getNave().getPesoConbustible());

        velocidadY.setText(format.format(simulacion.getNave().getVelocidadActualY()));
        velocidadX.setText(format.format(simulacion.getNave().getVelocidadActualX()));

        tiempoProximoChorro.setMaximum(Chorro.tiempoProximoChorroMx);
        tiempoProximoChorro.setValue(Chorro.tiempoProximoChorro);
        tiempoProximoChorro.setString(Chorro.tiempoProximoChorro + " / " + Chorro.tiempoProximoChorroMx);

        if (simulacion.getPausa()) {
            estatus.setSelectedIndex(1);
        } else if (simulacion.getFin()) {
            estatus.setSelectedIndex(2);
        } else {
            estatus.setSelectedIndex(0);
        }

        if (simulacion.getNave().isRecogio()) {
            exito.setText("Misión Exitosa");
            exito.setBackground(Color.GREEN);
        }

        relacionTiempo.setValue(simulacion.getRelacionMiliSeg());
        empujeYPos.setValue(simulacion.getNave().getEmpujeYPositivo());
        empujeYNeg.setValue(simulacion.getNave().getEmpujeYNegativo());
        empujeXNeg.setValue(simulacion.getNave().getEmpujeNegativo());
        empujeXPos.setValue(simulacion.getNave().getEmpujePositivo());

//        simulacion.setRelacionMiliSeg(relacionTiempo.getValue());
//        simulacion.getNave().setEmpujeY((int) empujeY.getValue());
//        simulacion.getNave().setEmpujePositivo((int) empujeXPos.getValue());
//        simulacion.getNave().setEmpujeNegativo((int) empujeXNeg.getValue());

        alturaY.setText("" + simulacion.getNave().getAltura());
        posicionX.setText("" + simulacion.getNave().getPosicion());

        if (simulacion.getNave().getPesoConbustible() <= 0) {
            empujeXNeg.setEnabled(false);
            empujeXPos.setEnabled(false);
            empujeYPos.setEnabled(false);
//            empujeXPos.setValue(0);
//            empujeXNeg.setValue(0);
//            empujeY.setValue(0);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem acercaDeItem;
    private javax.swing.JTextField alturaY;
    private javax.swing.JMenuItem ayudaItem;
    private javax.swing.JMenu ayudaMenu;
    private javax.swing.JProgressBar combustible;
    private javax.swing.JSpinner empujeXNeg;
    private javax.swing.JSpinner empujeXPos;
    private javax.swing.JSpinner empujeYNeg;
    private javax.swing.JSpinner empujeYPos;
    private javax.swing.JComboBox estatus;
    private javax.swing.JLabel exito;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JCheckBoxMenuItem pausaItem;
    private javax.swing.JTextField posicionX;
    private javax.swing.JSlider relacionTiempo;
    private javax.swing.JMenuItem salirItem;
    private javax.swing.JProgressBar tiempo;
    private javax.swing.JProgressBar tiempoProximoChorro;
    private javax.swing.JTextField velocidadX;
    private javax.swing.JTextField velocidadY;
    // End of variables declaration//GEN-END:variables
}
